name: e_store_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

#---------------PACKAGES-------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.20.2
  http: ^1.5.0
  logger: ^2.6.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.1.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firedart: ^0.9.8
  lottie: ^3.3.0
  connectivity_plus: ^7.0.0
  cloud_firestore: ^6.0.1
  cloudinary_flutter: ^1.3.0
  flutter_dotenv: ^6.0.0
  file_picker: ^10.3.3
  google_sign_in: ^6.3.0

  # Product Specific

#-------------- ./PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #---------------- LOCAL ASSETS ----------------#
  assets:
    - assets/logos/
    - assets/icons/payment/
    - assets/icons/categories/
    - assets/images/users/
    - assets/images/on_boarding/
    - assets/images/reviews/
    - assets/images/banners/
    - assets/icons/categories/
    - assets/images/products/
    - .env

  #---------------- LOCAL FONTS----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
