// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80EaNQ4NMSgia6OVJaFGOuVBUxePTvN4',
    appId: '1:1055679172292:web:5d9e1e9bb5cf1b0d460391',
    messagingSenderId: '1055679172292',
    projectId: 'e-store-5250a',
    authDomain: 'e-store-5250a.firebaseapp.com',
    storageBucket: 'e-store-5250a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjR-8allJl3RjfNKaG0JghbDv-KWgoe4',
    appId: '1:1055679172292:android:cdc417f76260dee1460391',
    messagingSenderId: '1055679172292',
    projectId: 'e-store-5250a',
    storageBucket: 'e-store-5250a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpDUsQx8OWMxxdO93ENP1DpC0xQelh7GA',
    appId: '1:1055679172292:ios:1ac3743c7f3c57e2460391',
    messagingSenderId: '1055679172292',
    projectId: 'e-store-5250a',
    storageBucket: 'e-store-5250a.firebasestorage.app',
    androidClientId: '1055679172292-lllo80hrkngjrh8s4d7iki219p89ss8r.apps.googleusercontent.com',
    iosClientId: '1055679172292-o2a6miu0vuf7ujbdtleirf84h3rss39i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStoreApp',
  );

}